# Generated by Django 5.1.1 on 2024-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presio', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('stock', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
            ],
        ),
    ]
