# Generated by Django 5.1.1 on 2024-11-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='Productos',
        ),
    ]
