# Generated by Django 5.1.1 on 2024-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0002_rename_materia_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='presio',
            field=models.IntegerField(),
        ),
    ]
