# Generated by Django 5.1.1 on 2024-11-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0003_alter_productos_presio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='presio',
            new_name='precio',
        ),
    ]
