# Generated by Django 5.1 on 2024-11-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0004_rename_presio_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
