# Generated by Django 5.1.1 on 2024-11-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_producto', models.CharField(max_length=6)),
                ('id_cliente', models.CharField(max_length=6)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('id_empleado', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
