# Generated by Django 5.1.1 on 2024-11-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direrccion', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_cliente', models.CharField(max_length=100)),
                ('metodo_de_pago', models.CharField(max_length=100)),
            ],
        ),
    ]
