# Generated by Django 5.1.1 on 2024-11-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
            ],
        ),
    ]
