# Generated by Django 5.1 on 2024-11-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
