# Generated by Django 5.1 on 2024-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores_app', '0002_alter_proveedor_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
