# Generated by Django 5.1.1 on 2024-11-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('horario', models.CharField(max_length=100)),
                ('gerente', models.CharField(max_length=100)),
                ('administrador', models.CharField(max_length=100)),
            ],
        ),
    ]
