# Generated by Django 5.1 on 2024-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados_app', '0002_alter_empleado_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechadeingreso',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
